# Generated by Django 4.2.3 on 2023-07-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budeget',
            name='total_budget_amount',
        ),
        migrations.AddField(
            model_name='budeget',
            name='budget_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.budeget')),
            ],
        ),
    ]
