# Generated by Django 4.2.3 on 2023-07-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_budeget_total_budget_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
