# Generated by Django 4.2.3 on 2023-08-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_allocated_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
