# Generated by Django 4.2.3 on 2023-08-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
