# Generated by Django 4.2.3 on 2023-08-09 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_category_allocated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budeget',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budeget',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
